test:
  product_url: 'http://localhost:3000'
  coupon_url: 'http://localhost:4000'
development:
  product_url: 'http://0.0.0.0:3000'
  coupon_url: 'http://0.0.0.0:4000'
production:
  product_url: 'http://0.0.0.0:3000'
  coupon_url: 'http://0.0.0.0:4000'
